# Numpy Tutorial: Numerical Linear Algebra
This notebook covers essential numpy operations for working with vectors and matrices, including matrix operations critical for scientific computing.

## Introduction to NumPy Arrays
### Key Concepts:
- Numpy arrays vs Python lists (efficiency/structure)
- Creating basic vectors/matrices

In [2]:
import numpy as np

## Arrays
These are the foundational objects for numerical linear algebra. We can create vectors and matrices (and even higher-dimensional rectangular arrays, collectively called tensors) in numpy. This has several advantages: 
- In numpy, arrays all have the same data type and must be rectangular, just like matrices
- These arrays are stored in a way that makes computation efficient. Python itself is slow compared to other language. numpy actually translates our arrays and their operations into a different programming language to run it, which makes everything much faster.

### Array Creation Functions
#### Useful constructors:
- `np.array()` creates an array from a Python list or tuple
- `np.zeros()` creates matrices of all zeros
- `np.ones()` creates matrices of all ones 
- `np.eye()` for identity matrices
- `np.arange()` creates an array with evenly spaced values within a given interval
- `np.linspace()` creates an array with a specified number of evently spaced values over a given interval
- Various methods for creating random matrices where the elements are drawn from different statistical distributions

In [3]:
# Vectors (1D array)
v = np.array([1, 2, 3])
print("Vector:", v, " | Shape:", v.shape)

# Matrices (2D arrays)
m = np.array([[1, 2], [3, 4]])
print("Matrix:\n", m, "\nShape:", m.shape)

zero = np.zeros((3,4))
print('A 3x4 of zeros: ')
print(zero)

ones = np.ones((2,2))
print('A 2x2 of ones: ')
print(ones)

# Identity matrix (3x3)
I = np.eye(3)
print ('Identity Matrix:')
print(I)

# arange
arange_arr = np.arange(0,10,2)
print('arange arr: ')
print(arange_arr)

# linspace
linspace_arr = np.linspace(0,1,11)
print(f'linspace arr: ')
print(linspace_arr)

Vector: [1 2 3]  | Shape: (3,)
Matrix:
 [[1 2]
 [3 4]] 
Shape: (2, 2)
A 3x4 of zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
A 2x2 of ones: 
[[1. 1.]
 [1. 1.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange arr: 
[0 2 4 6 8]
linspace arr: 
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Array Attributes
- `.shape` for dimensions
- `.ndim` for number of axes
- `.dtype` data type

In [4]:
A = np.array([[1, 2], [3, 4]])
print("A = \n", A)
print("Dimensions:", A.shape)
print("ndim:", A.ndim)
print("Data Type:", A.dtype)

A = 
 [[1 2]
 [3 4]]
Dimensions: (2, 2)
ndim: 2
Data Type: int64


In [5]:
A = np.array([[1.2, 2.3], [3.3, 4]])
print("A = \n", A)
print("Dimensions:", A.shape)
print("Data Type:", A.dtype)

A = 
 [[1.2 2.3]
 [3.3 4. ]]
Dimensions: (2, 2)
Data Type: float64


In [6]:
print("arange_arr: ", arange_arr)
print("arange_arr shape: ", arange_arr.shape)

arange_arr:  [0 2 4 6 8]
arange_arr shape:  (5,)


## Basic Array Operations
### Element-wise operations
- Addition, Subtraction, Scalar Multiplication

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Element-wise addition
d = a * 2  # Scalar multiplication

### Mathematical Functions:

- Basic Arithmetic: `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`, `np.power()`, `np.mod()`. 
- Trigonometric: `np.sin()`, `np.cos()`, `np.tan()`, `np.arcsin()`, `np.arccos()`, `np.arctan()`. 
- Hyperbolic: `np.sinh()`, `np.cosh()`, `np.tanh()`. 
- Exponential and Logarithmic: `np.exp()`, `np.log()`, `np.log10()`, `np.log2()`. 
- Rounding and Absolute Values: `np.round()`, `np.floor()`, `np.ceil()`, `np.absolute()`, `np.fabs()`. 
- Square Root: `np.sqrt()`. 

In [11]:
sqrt_arr = np.sqrt(a)
log_arr = np.log(a)
print('sqrt_arr = \n', sqrt_arr)
print('log_arr = \n', log_arr)

sqrt_arr = 
 [1.         1.41421356 1.73205081]
log_arr = 
 [0.         0.69314718 1.09861229]


## Indexing and Slicing

NumPy array indexing refers to the methods used to access and modify elements or subsets of elements within a NumPy array. This process allows for precise manipulation of data stored in arrays, regardless of their dimensionality.

### Single Element Access
Elements are accessed using zero-based integer indices within square brackets. For multi-dimensional arrays, indices for each dimension are provided, separated by commas (e.g., `array[row_index, column_index]`).

In [11]:
arr = np.array([6, 3, 2, 1, 9, 10])
matrix = np.array([[4, 2], [8, 0]])
element = arr[0]
row_col = matrix[0, 1]
print(f"arr is {arr} and element is {element}.")
print(f"matrix is \n{matrix}\nand row_col is {row_col}.")

arr is [ 6  3  2  1  9 10] and element is 6.
matrix is 
[[4 2]
 [8 0]]
and row_col is 2.


### Negative Indexing
Elements can be accessed from the end of the array using negative indices, where `-1` refers to the last element, `-2` to the second-to-last, and so on.

In [12]:
element = arr[-1]
print(f"arr is {arr} and element is {element}.")

arr is [ 6  3  2  1  9 10] and element is 10.


### Slicing
NumPy array slicing allows for accessing subsets of a NumPy array, similar to slicing Python lists, but extended to N dimensions. The general syntax for slicing is array `[start:stop:step]`.

- `start`: The index of the first element to include in the slice (inclusive). If omitted, it defaults to the beginning of the dimension.
- `stop`: The index of the last element to include in the slice (exclusive). If omitted, it defaults to the end of the dimension.
- `step`: The interval between elements to select. If omitted, it defaults to 1. A negative step reverses the order of elements. 

In [13]:
slice_arr = arr[1:4]
print(f"arr is {arr} and slice_arr is {slice_arr}.")

arr is [ 6  3  2  1  9 10] and slice_arr is [3 2 1].


For multi-dimensional arrays, slicing is applied independently along each dimension, separated by commas. For example, `array[row_slice, column_slice]` would slice a 2D array.

In [16]:
slice_matrix = matrix[:, 0] # First column
print(f"matrix is\n{matrix}\nand slice_matrix is {slice_matrix}.")

matrix is
[[4 2]
 [8 0]]
and slice_matrix is [4 8].


Notice that even when you take a single column on an array, you get a 1D array, which numpy displays as a row.