# Dot Products and Matrix Operations

In [3]:
import numpy as np

## Critical Operations:
- `np.dot()` vs `@` operator
- Difference between element-wise multiplication (`*`) and dot product

In [4]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print('vector 1:\n', v1)
print('vector 2:\n', v2)

# Dot product
print("Dot Product:", v1 @ v2) 
print("Another way to do the dot product:", v1.dot(v2)) 
print('Using the * operator (element-wise multiplication):\n', v1 * v2)

vector 1:
 [1 2]
vector 2:
 [3 4]
Dot Product: 11
Another way to do the dot product: 11
Using the * operator (element-wise multiplication):
 [3 8]


In [5]:
# Matrix multiplication example
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('matrix A:\n', A)
print('matrix B:\n', B)

print("Matrix Product:\n", A @ B)
print("Element-Wise Multiplication:\n", A * B)

matrix A:
 [[1 2]
 [3 4]]
matrix B:
 [[5 6]
 [7 8]]
Matrix Product:
 [[19 22]
 [43 50]]
Element-Wise Multiplication:
 [[ 5 12]
 [21 32]]


In [6]:
# Matrix-vector multiplication - notice the dimension and how it is displayed
print(A@v1)

[ 5 11]


## Transpose Operation
- Use `.T` attribute to get the transpose of a matrix.

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", matrix)
print("Original shape:", matrix.shape)
print("Transposed:\n", matrix.T)
print("Transposed shape:\n", matrix.T.shape)

Original:
 [[1 2 3]
 [4 5 6]]
Original shape: (2, 3)
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Transposed shape:
 (3, 2)


## Norm Calculations
### Vector and matrix norms:
- L1/L2 norms with `np.linalg.norm()`

In [9]:
v = np.array([3, -4])
print('vector v:', v)
print("L2 norm (magnitude):", np.linalg.norm(v)) # Should be 5
print('L1 norm:', np.linalg.norm(v, ord=1)) # Should be 7

A = np.array([[1, 2], [3, 4]])
print('matrix A:\n', A)

print("1-Norm of matrix:", np.linalg.norm(A, ord=1))
print("infinity-Norm of matrix:", np.linalg.norm(A, ord=np.inf))
print("Frobenius norm of matrix:", np.linalg.norm(A, ord='fro'))

vector v: [ 3 -4]
L2 norm (magnitude): 5.0
L1 norm: 7.0
matrix A:
 [[1 2]
 [3 4]]
1-Norm of matrix: 6.0
infinity-Norm of matrix: 7.0
Frobenius norm of matrix: 5.477225575051661
